### PR TITLE
Issue #326: Fix statically called non-static method.

### PR DESCRIPTION
**Pull request by t4k**
Addresses #326.

## Review Procedure
Enable PHP error reporting for E_DEPRECATED and load any CORAL page besides the root index and there will be Deprecated messages. Apply this fix and Deprecated messages for this issue are no longer there.

### CODE REVIEW

**Comment by remocrevo** [comment]
@t4k Watch out for whitespacing (tabs vs. spaces) as seen here:
https://patch-diff.githubusercontent.com/raw/coral-erm/coral/pull/327.diff

**Comment by t4k** [comment]
My interpretation of the discussion at the end of #55 was that we would begin to use the new coding guidelines on all new patches, regardless of the state of the old code, and not update old code just for formatting issues, unless a separate formatting issue is being addressed.

**Comment by t4k** [comment]
The new `.editorconfig` does solve the issue locally. It sets tab width to 2, which makes all the indents visually consistent. I’m not sure if we can set GitHub to respect those settings online though.

**Comment by veggiematts** [comment]
Out of the space-tabs issue, the fix is ok. I would merge this.

**Comment by veggiematts** [comment]
Moreover, the API is broken without this patch when error_reporting = E_ALL
This is a serious bug, I'm merging this.

**Pull request merged**
