### PR TITLE
Issue 489 fix subscription date fields

### LINKED ISSUE #489: Subscription dates not set correctly for orders during upgrade
When upgrading to Coral 3.0.0 from 2.0.1 the upgrade script doesn’t migrate all the Acquisitions data to the new ResourceAcquisitions table. The columns currentStartDate and currentEndDate are kept in the Resource table while all newly created orders are instead given today’s date in both subscriptionStartDate and subscriptionEndDate (“NOW()” on line 100 in the [upgrade SQL](https://github.com/coral-erm/coral/blob/master/resources/install/protected/3.0.0/002-350.sql)).

As far as we can tell there is no way to access/edit currentStartDate or currentEndDate from the UI in 3.0.0., and the newly created orders have incorrect dates. We believe this to be a bug. 

Preferably the dates from currentStartDate/EndDate should be migrated like the other Acquisition/Order data during the upgrade (to subscriptionStartDate/EndDate), and then drop the columns from Resource.

### PR DESCRIPTION
**Pull request by jeffnm**
This should fix #489 

It includes SQL to copy the `currentStartDate` and `currentEndDate` fields from the Resource table to  the ResourceAcquisition table's `subscriptionStartDate` and `subscriptionEndDate`.  

There are also changes to code that utilizes those fields in the Resource table and class.

## Testing the SQL
Since this pull request does not include the 3.0.1 upgrade code, the SQL will not be run automatically. To test it, you will need a database that has the dates in Resource `currentStartDate` and `currentEndDate` and the automatically created dates in ResourceAcquisition `subscriptionStartDate` and `subscriptionEndDate`. When you apply the SQL file (`3.0.1/002-489.sql`) it will copy the columns and then drop the old ones. 

## Testing the other changes
Make sure you can see all the Order dates you expect in Resources and in Licensing's Calendar.

### CODE REVIEW

**Comment by poacherone** [comment]
Tested and works as intended, as far as I can see (dates updated and displayed correctly). Note that I haven't got anything in my calendar in Licensing, but I am not sure how to set that up.

**Comment by veggiematts** [comment]
Quick thoughts:
  - resource dates are still used in summary.php (resource -> Helpful Links -> print view). We should fix this.
  - shouldn't we also modify `install/protected/3.0.0/002-350.sql` so people that haven't upgraded to 3.0.0 yet will directly have the correct dates?

**Comment by jeffnm** [comment]
I pushed changes to keep the old columns, revert the API to access those old columns, and fix the summary.php (print view) display.

The question of whether to modify the `install/protected/3.0.0/002-350.sql` file or not is interesting. My initial thought was no, the 3.0.1 patch will be immediately applied for anyone who is installing 3.0.0 for the first time. However, I think copying everything at the time of install/upgrade will be better. I'll make those changes.

**Comment by veggiematts** [comment]
Tech review ok for me.

**Pull request merged**
