### PR TITLE
Improvements to the order dropdown list

### PR DESCRIPTION
**Pull request by veggiematts**
- Sort orders by subscription start date desc, subscription end date desc
 - Select the first order that is currently active (start date <= today => end date)
 - Show the order's organization after the dates

Before:
orders_before

After:
orders_after

### CODE REVIEW

**Comment by veggiematts** [comment]
Fix for #451

**Comment by poacherone** [comment]
We have tested this PR and it works as intended. The sorting makes sense, and the fact that you "land" on the current order is a good improvement (you might be adding new orders for the coming year, but the one still active should be the one currently used)!

The only tiny issue we faced was that the dropdown box doesn't have a fixed length, so if it is a very long organization name it will extend to cover the full name which makes it look a bit strange. But width issues are found elsewhere in Coral, so perhaps this should not be covered by this PR but be a separate (bigger) issue?

**Comment by veggiematts** [comment]
Thank you for the feedback!

> The only tiny issue we faced was that the dropdown box doesn't have a fixed length, so if it is a very long organization name it will extend to cover the full name which makes it look a bit strange

In fact, the dropdown has a max size of 1000px, which is roughly the available length in Coral interface. So having very long organization names will make it look perhaps a bit strange, but not broken :)

**Comment by sbouis** [comment]
Hello,
why do we add the organization names here? Is it from another PR or is it from this one?
For me, it's not necessary, but perhaps other libraries need it.

**Comment by sbouis** [comment]
Ok, just read the beginning of this PR : "Show the order's organization after the dates"
Is it asked by other libraries?

**Comment by veggiematts** [comment]
Yes, it was. This dev was sponsored by one of our customers.

**Comment by sbouis** [comment]
Ok, I just wonder.

**Comment by veggiematts** [comment]
@jeffnm I would be in favor of adding this to 3.0.1, even if it is not a bugfix, but it is a small enhancement that improves display and usability. What do you think?

**Comment by jeffnm** [comment]
@veggiematts I'm also in favor, I've added it to the project and tested it. It works as described. Is there any implication from #489 for this? If you don't see any issues there, then let's merge it.

**Comment by veggiematts** [comment]
> Is there any implication from #489 for this

No, #489 can (and should) be addressed separately.

> If you don't see any issues there, then let's merge it.
Let's do this :)

**Pull request merged**
