### PR TITLE
Issues 103, 403: Fix selected language in dropdown when language cookie is not set.

### PR DESCRIPTION
**Pull request by veggiematts**
PR Not found :)

Fixes issues #103 and #403 

Test plan:
 - Clear your Coral language cookie
 - Without changing language (no cookie set), check that the browser's language is selected by default in language dropdown lists everywhere in Coral.
 - Change the language (language cookie is set), check that the language you chose is selected in language dropdown lists everywhere in Coral.

### CODE REVIEW

**Comment by t4k** [comment]
This works for me. I'll merge it.

**Comment by scottvieira** [comment]
@t4k Was this a bug from 2.01 or a 3.0 beta fix?

**Comment by t4k** [comment]
@scottvieira I'm not sure. I only noticed this testing 3.0 after the German translation was added. I would read over #103 and #403 to deduce.

**Comment by veggiematts** [comment]
The bug was here since the introduction of translations. However, you didn't notice it before german was introduced, because english was the first option, alphabetically, and thus selected by default :)

But for french people for example, it was a bug from 2.0.1

**Comment by scottvieira** [comment]
@veggiematts That's very helpful.  Thanks!

**Pull request merged**
