### PR TITLE
Fix licensing calendar

### PR DESCRIPTION
**Pull request by veggiematts**
The calendar page in the licensing module is currently broken: it never returns any data.
This patch intends to fix this.

Please note that this is a hotfix. It does return some data now, but I didn't check that said data is what is expected.

Please test this, and report any functional problem.

### CODE REVIEW

**Comment by poacherone** [comment]
This PR joins the tables correctly, giving results in the table. But the actual dates (how long it has expired) doesn't show, only showing 0. To fix this line 195 in licensing/calendar.php should be changed from “currentEndDate” to “subscriptionEndDate”.

**Comment by veggiematts** [comment]
@poacherone can you confirm the fix is ok with your modification ?

**Comment by sbouis** [comment]
I tried this one.
After changing settings in Licensing admin (Authorized Sites; Days After Subscription End; Days Before Subscription End; Resource Types), I can confirm that with this correction I can see in Calendar the Upcoming License Renewals that I coudln't see without.
It lists the resources with a Current Sub End set  in an  order that is beetween  Current Sub End - Days After Subscription End and  Current Sub End + Days Before Subscription End.

I only noticed an encoding problem with french accents.

**Comment by veggiematts** [comment]
Thanks for the feedback, @sbouis 
I'm merging this, can you create a separate issue for the encoding problem ?

**Pull request merged**
