### PR TITLE
Making the content areas wider for resource content areas.

### PR DESCRIPTION
**Pull request by jcraitz**
We've noticed that since version 2.0, content areas have been very narrow for different resource views/tabs.  This pull request is an effort to widen those areas since we're not really using a responsive design.

### CODE REVIEW

**Comment by veggiematts** [comment]
Could you please provide screenshots of before/after your modifications?
I've seen a difference of a few pixels on the "product" tab, but no difference on the "acquisitions" tab.

**Comment by jcraitz** [comment]
It becomes particularly noticeable when resources have extremely long titles.

Current master:
screen shot 2017-12-21 at 11 45 04 am

After css changes:
screen shot 2017-12-21 at 11 45 14 am

**Comment by veggiematts** [comment]
Tested ok. I'm merging this.

**Comment by scottvieira** [comment]
I am moving this along in the project without any documentation.  It doesn't seem like it is needed here.

**Pull request merged**
