### PR TITLE
Update externalLoginSubmitForm.js

### PR DESCRIPTION
**Pull request by mirkh**
In Usage module: The modal "getLoginForm" will not open. 

Usage module Home, click on a Platform entry, click on the tab Logins, click "add new login" There will be a waiting image, but the modal is not opening.

The problem was two unclosed parentheses in the javascript file.

### CODE REVIEW

**Comment by andyp-uk** [comment]
This fix should really go into coral-erm:development initially.

**Comment by andyp-uk** [comment]
I have tested the fix in any case and can approve merging into coral-erm:development.

**Comment by mirkh** [comment]
Thanks Andy! / Maria

**Review by HitScan — APPROVED** [review]
Corrects the issue.

**Comment by andyp-uk** [comment]
Opened https://github.com/coral-erm/coral/pull/699 to merge these changes into development branch.

**Pull request closed without merging**
