### PR TITLE
Remove orders on resource deletion

### PR DESCRIPTION
**Pull request by veggiematts**
Since contacts are now linked to orders, orders are to be deleted when a resource is deleted (note: I have the feeling that this was already done before, but it may have been lost in a merge / rebase).

Also fixes #348

### CODE REVIEW

**Comment by jcraitz** [comment]
I saw at least two more functions in the Resource class that are now broken/not-needed.  Not sure if they've been refactored like you did here for contacts.
- removeResourceSteps()
- removeResourceNotes()

**Comment by veggiematts** [comment]
removeResourceSteps isn't called anywhere in Coral (it was already the case in master) so it can be safely removed.

removeResourceNotes is indeed broken, I'll provide a fix.

**Comment by veggiematts** [comment]
Resource contacts and notes are now properly removed on resource deletion.

**Comment by veggiematts** [comment]
_Test plan:_

**For notes:**
 - create some notes on resource level (Product tab, in this caseResourceNote.entityID = Resource.resourceID)
 - create some notes on order level (Acquisitions, Access and Cataloging tabs, in this case ResourceNote.entityID = ResourceAcquisition.resourceAcquisitionID)
 - delete the resource
 - check in the database that all notes (both on resource and order level) have been deleted.

**For contacts:**
 - create contacts
 - archive some of them
 - delete the resource
 - check in the database that all contacts have been deleted, as well as ContactRoleProfiles values for these contacts

**Comment by veggiematts** [comment]
This has to be merged before releasing the beta, to avoid database inconsistencies.

**Comment by jeffnm** [comment]
The note and contact deleting worked as expected. However, when deleting a resource I received the following at the top of the page:
```
Warning: Invalid argument supplied for foreach() in /var/www/html/resources/admin/classes/domain/Resource.php on line 1408
Resource successfully deleted.
```

**Comment by veggiematts** [comment]
Fixed.

**Comment by veggiematts** [comment]
@jeffnm Did you have a chance to test this again with the last fix?

**Comment by jeffnm** [comment]
@veggiematts sorry, I didn't get to it yet.

**Comment by jeffnm** [comment]
I was able to test this and it seems to work well. Merging.

**Pull request merged**
