### PR TITLE
Test suite

### PR DESCRIPTION
**Pull request by connordelacruz**
Wrote additional acceptance tests for the Licensing, Organizations, Resources, and Usage modules and added some information to TESTS.md.

### CODE REVIEW

**Comment by bdroubay** [comment]
Hi all,

We discovered many areas where the translations were missing -- mostly in the side menus in the resources and usage modules. In order to get POEdit to recognize the text as translatable strings, I had to make some coding changes. I am waiting for the translation strings to come back from our translation team, but I would like to push the programming changes to master. Are there any objections?  They are not extensive, and I have tested the functionality. Everything seems to be working properly.

I will push the changes if everyone agrees. The French, traditional and simplified Chinese translations should be ready next week, and I will push the translations then.

Thanks,

Brad

**Comment by tuxayo** [comment]
@connordelacruz For some reason the DB is no more reset despite the `resetTestDatabase()` function in `tests/_support/Helper/Acceptance.php` being called.

Can you also reproduce this issue?
- manually switch to the test environment by editing `admin/configuration.ini`
- create/edit/delete whatever in Coral (login with user: coral_test, passphrase: coral_test)
- run the tests
- manually switch again to the test environment
- check that your creation/edition/deletion is still there. Which should not be the case if the DB reset worked.

I got failures, but hopefully there are related to the previous issue https://0bin.net/paste/C34oQq2vvJlBX+uB#3IJ8skHmF6rduFj-eyxqfYYLX6F34XmAEdU1KAaW4hq

**Comment by tuxayo** [comment]
@bdroubay Is your message related to this PR? It rather seem related to #85

**Comment by connordelacruz** [comment]
@tuxayo I attempted to reproduce this issue but was not able to:
* manually switched to test environment by editing `admin/configuration.ini`
* created resource named "shouldn't see this" as user coral_test
* ran tests
* manually switched back to the test environment
* clicked on resources, which brought me to the authentication page. On the authentication page, there was a message saying that I was already logged in as coral_test, but I was able to sign in as coral_test anyway
* the resource created prior to running the tests was not there

The only unexpected behavior I encountered was the message saying "You are already logged on as coral_test", but that message also appeared when I didn't change back to the test environment after running the tests, so it may be related to a cookie that was set when I created the resource in the test environment before running the tests. In the production environment, I do not have a user coral_test, so I couldn't actually sign in as them.

**Pull request merged**
