### PR TITLE
Rf39958 email reminder content

### PR DESCRIPTION
**Pull request by jeffnm**
See original pull request: #155

### CODE REVIEW

**Comment by jeffnm** [comment]
I'm putting this on the 2.0 milestone for the moment since it sounds like it's a key part of the workflow feature that's already in the 2.0 beta. 

I'm also adding the help wanted label, specifically for someone besides the developer and originator to test it. If no one is able to test it before 2.0 release, we'll change the milestone to 2.1 beta and make sure to get it in then.

**Comment by jeffnm** [comment]
@scottvieira I'm sure you've been busy, but is this still a pull request that you'll be able to test?

**Comment by scottvieira** [comment]
@jeffnm Yes, I still want to test this so it can be included in 2.0.  Unfortunatley I will be out the rest of the week for a conference.  I will try again next week to get this done.

**Comment by jeffnm** [comment]
Based on the feedback at the last SC meeting, I think this is ready to merge.

**Pull request merged**
