### PR TITLE
Removing old installer code

### PR DESCRIPTION
**Pull request by jcuenod**

### CODE REVIEW

**Comment by jeffnm** [comment]
@jcuenod can you provide a brief change long for this pull request? @t4k will be reviewing it, but it would be helpful to have an overview of what's new. Thanks!

**Comment by jcuenod** [comment]
Hey @t4k, let me give you the highlights for each commit:

- ab0fea8: this commit literally just removes old installer code (we wouldn't want someone reading an old set of instructions or something and running it, it's also completely unused now). So this commit involves the following line changes: +0 −9,948.
- ab30990: ignore it, this is just a sync with master
- effe5d0: Handle db host being on other server (cf. #175)
- 6c8bd34: Security fix, protecting common config file on apache hosts (adding htaccess in `/common`)
- 07217c5: Improve language of error message (irrelevant, to be honest) [modified a string]
- 7ea2b1f: Updated user instructions when installing (the message was old and needed to be updated because of the way the new installer/upgrader works) [modified a string]
- d6f4752: It's worth reading #188 for this one. It began as just updating a string in a conf file but the string was non-standard and I ended up finding that `reportsModule` was preferable to `reportingModule` (which was the original) but the more deep rooted issue was the string `usageDatabase` which should be the more standard `usageDatabaseName`.

**The ones that actually need attention and should definitely be tested** are effe5d0 and d6f4752. Technically I should include 6c8bd34 but its pretty simple.

**Comment by t4k** [comment]
Left a comment in #175 because I don’t think this is fixed yet.

**Comment by t4k** [comment]
#175 is fixed and so I will say this whole PR is good. (@jeffnm tested the #188 parts)

**Comment by jeffnm** [comment]
Thanks @t4k 

I'll merge it.

**Comment by jcuenod** [comment]
Thanks, sorry for what turned out to be a gigantic pull request.

**Pull request merged**
