### PR TITLE
New fields for acquisitions: Tax (Pr63 in previous non merged repos)

### PR DESCRIPTION
**Pull request by PaulPoulain**
As asked in pull request https://github.com/ndlibersa/resources/pull/50 , here's a new pull request featuring only the tax fields:

    Add new fields to the enhanced acquisitions mode:
        Price Tax Excluded
        Tax Rate
        Price Tax Included

    Price Tax Included and Payment Amount will be automatically prefilled accoring
    to the Price Tax Excluded and Tax Rate values.

### CODE REVIEW

**Comment by remocrevo** [comment]
This pull req seems to include the code from pull req #2 (Session Abstraction). @PaulPoulain was this an accident, or did you intend for #2 to be merged first?

**Comment by PaulPoulain** [comment]
Le 17/03/2016 13:40, remocrevo a écrit :
>
> This pull req seems to include the code from pull req #2 
> <https://github.com/Coral-erm/Coral/pull/2> (Session Abstraction). 
> @PaulPoulain <https://github.com/PaulPoulain> was this an accident, or 
> did you intend for #2 <https://github.com/Coral-erm/Coral/pull/2> to 
> be merged first?
>
Yikes... no, it's an accident. I'll fix this ASAP !

-- 
Paul Poulain, Associé-gérant / co-owner
BibLibre, Services en logiciels libres pour les bibliothèques
BibLibre, Open Source software and services for libraries

**Comment by jsavell** [comment]
I'm closing this request and reopening it as a new PR. Github is registering 14 new commits and intractable merge conflicts when there should only be 3 commits. The other 11 commits contain code that has already been merged into master. A new PR based on the current master branch will resolve this.

**Comment by tuxayo** [comment]
> Github is registering 14 new commits

Sorry, at least 7 of these are unrelated and mine. :-(
I did a typo in the message of one commit (referencing `#3` instead of `#36`).
And after doing various rebases to fix some errors and sync with master, that duplicated the said commit...

**Pull request closed without merging**
