### PR TITLE
Reports: Downloaded XLS file now has the correct file suffix

### PR DESCRIPTION
**Pull request by PerplexedTheta**
Please see [issue 695](https://github.com/coral-erm/coral/issues/695)

### CODE REVIEW

**Comment by PerplexedTheta** [comment]
Hi,

Any update on this request?

Thanks,
Jake

**Comment by andyp-uk** [comment]
What you've done looks fine. Someone will need to test then merge it. If nobody else gets to it first, I will very likely do this myself before the next release.

**Comment by andyp-uk** [comment]
Having a look at the issue myself, I see the file generated isn't actually an XLS file. Adding an XLS file suffix makes it easier for users to open the file with Excel, but there is still a warning that the file could be corrupted or unsafe. 

Other members of the CORAL steering committe might want to give their opinion before this is merged.

**Comment by gmcharlt** [comment]
While looking at this, I ran across the following: back in 2016, Microsoft released a [security update](https://support.microsoft.com/en-us/topic/ms16-088-description-of-the-security-update-for-excel-2013-july-12-2016-5dd955cd-4464-47bf-b7e3-5ab2b08e5953) that made Excel refuse to load HTML files that were given an .xls extension at all (unless the website was added to a trusted list). Microsoft [subsequently changed the behavior](https://support.microsoft.com/en-us/topic/august-9-2016-update-for-excel-2016-kb3115438-8c93049f-a1b7-8919-6675-ba8491ef4567) so that such files would instead be opened in "protected view". Consequently, there are theoretically some users who may not be able to open such files in Excel.

In any event, I do get a warning from Excel that the file may be corrupted. Better long term options might be to provide a CSV export option and/or a library to generate true XLS or XSLX output.

**Pull request closed without merging**
