### PR TITLE
Update PR #170 to resolve merge conflicts.

### PR DESCRIPTION
**Pull request by t4k**
There were merge conflicts in PR #170 (old PR #153) that needed to be resolved. Also included an isset() call to reduce notices in the logs.

This is the second part of the review and approval of everything in #8.

### CODE REVIEW

**Comment by t4k** [comment]
One comment about the functionality in this PR that should be added to its own issue once this is merged:

Imported CSV files uploaded to the attachments directory are silently overwritten if they have the same filename as an existing file in that directory. This could cause confusion because the links on the Import History page to the previously uploaded files with the same name(s) would all link to the most recently uploaded file.

I don’t think this is a blocking issue, but would certainly require a Known Issues note and some documentation.

**Comment by scottvieira** [comment]
@t4k How hard would it be to just fixed the code so that it doesn't overwrite the existing file without user intervention?

**Comment by techsvcslib** [comment]
This is my preference also.

Steve

On Aug 4, 2017, at 11:37 AM, Scott Vieira <notifications@github.com<mailto:notifications@github.com>> wrote:


@t4k<https://github.com/t4k> How hard would it be to just fixed the code so that it doesn't overwrite the existing file without user intervention?

**Comment by t4k** [comment]
@scottvieira @techsvcslib I am trying to concentrate on getting this pull requests up to speed right now so we can at least merge them.

Adding file renaming or rejecting would be a sizable amount of code that we really should develop for the project as a whole. There are many places where file uploads happen in CORAL and we should write code that will handle this globally when we have a chance. An issue should be opened for it.

The thing is, this silent overwriting behavior is how it was already working. By exposing upload history, we are just making records for data that was sort of ephemeral before.

**Comment by scottvieira** [comment]
@t4k @techsvcslib I agree.  Putting this down as an issue works for me.  I don't know PHP, but I'm surprised there isn't existing code or a function for this.

**Comment by t4k** [comment]
@scottvieira Yes, there are existing patterns to use for something like this, but there is not just something one can drop into existing code that will work with the existing application without considering how to integrate it with the rest of the codebase.

**Pull request merged**
