### PR TITLE
SirsiDynix Issues: Not all dates are formatted based on setting in directory.php

### PR DESCRIPTION
**Pull request by queryluke**
# 1. Management Module
default dates should be formatted to the format set in directory.php

## Review Procedure
1. Edit `managment/directory.php`, line 73 to a different date format (d-m-Y)
2. Edit `management/js/common.js`, line 39 to a matching date format (dd-mm-yyyy)
3. Add new document, default date should be displayed in the new format
4. On changing the date, it should be displayed in the new format
5. Document should save without error
6. Click on newly created document. Last document revision date should be displayed
in the new format
7. Edit the document, date should be in new format
8. Change date, should be in new format
9. should save without error

# 2. Resources Module, My Queue
1. Dates in the My Queue > Saved Requests & Submitted Requests should be formatted to the format
set in directory.php

## Review Procedure
1. Edit `resources/directory.php`, line 112 to a different date format (d-m-Y)
2. Go to "My Queue"
    - If there are no saved or submitted requests, add one of each
3. The __Date Created__ for both the Saved and Submitted requests should both
display in the new format.

# 3. Resources Module, Acquisition Form
Remove the input placeholder on the acquisition form. It is hardcoded with
"mm/dd/yyyy", which cannot be adjusted until date format is moved to a configuration file.
Removing it completely follows the convention of all other date input fields. I.e., no others have a placeholder.

## Review procedure
1. Create a new resource
2. Click on the new resource
3. Select "Acquisitions" from the left nav menu
4. Click "Edit Order Information"
5. "Sub Start" & "Current Sub End" should not have a placeholder

### CODE REVIEW

**Comment by veggiematts** [comment]
Could you resolve the conflicts, please?

**Comment by queryluke** [comment]
@veggiematts done. Thanks for the ping.

**Comment by veggiematts** [comment]
Test plan is now a bit different: the date format is in common/common_directory.php line 80.
Tested ok. Code's ok.
Please note that "Sub Start" and "Sub End" in Cost Informations still have placeholders when enhancedCostHistory is enabled.
@queryluke do you want to fix this in this PR or later in a separate one?

**Comment by queryluke** [comment]
@veggiematts Thanks, I've removed those placeholders.

**Pull request merged**
