### PR TITLE
Moved install instructions from wiki to INSTALL.md

### PR DESCRIPTION
**Pull request by tuxayo**
### What has been done?
- Moved them into INSTALL.md file
  - So @jeffnm will be able to easily update them for the new installer
  - So anyone will be able to propose enhancements while all the wiki is moved to a repo (especially when testing the new installer)
  - An INSTALL.md file is a common practice when the instructions don't fit in the README
- Updated and completed the instructions
  - Aborbed the following sections of the [Tech doc](https://github.com/Coral-erm/Coral/wiki/CORAL-Technical-Documentation) page of the wiki
    - Server-Side Requirements and Setup
    - Installation
    - Resources Alerts Scheduling
    - Additional CORAL Resources customization options
    - New to PHP?
    - Possible issues during installation (or - things to verify if CORAL is not working at this point)
### Proposed new version of `CORAL-Technical-Documentation`

See the next comment. To import it, someone who have the edit privileges on the wiki should will also be able to click on `edit` on my comment to get the markdown of it and copy it in the wiki

### CODE REVIEW

**Comment by tuxayo** [comment]
## Supported Browsers 
* Current and recent Firefox, IE, Safari, Seamonkey, Opera, and Chrome versions are all supported 
* Requires Browser to have Javascript enabled – the CORAL interface relies heavily on AJAX, JQuery and JQuery plugins 

## Application Architecture 
CORAL is written using object oriented code.  All classes and configuration are defined under the 
`/admin/` directory.  The admin directory has an `.htaccess` file in order to prevent web users from 
accessing config data. 

`/directory.php` is used to load all of the classes.  This is called from every page and for the ajax functions 
and also contains some globally used functions. 

`/admin/configuration.ini` defines config settings (module settings, database and ldap) 

Common classes are in `/admin/classes/common/` - includes configuration, database connection, LDAP, 
Utility, Email 

### Database 
All database tables have matching classes and all database SQL code is done within methods of these 
classes. 

Every class extends the DatabaseObject for generic  SQL handling (retrieving all values, inserts, updates, 
deletes).  DatabaseObject is in `/admin/classes/common/` and the database classes are located in 
`/admin/classes/domain/` 

### Web side 
Pages - `admin.php`, `index.php`, detail view scripts and reports are all shells for positioning divs.  Within 
each div data is updated via ajax calling `ajax_htmldata.php`.  This way when changes are made to the 
data the display can be immediately updated without needing to refresh the entire page. 

A jquery plugin called thickbox is used to display the “popup” forms with the grayed out background. 

`ajax_forms.php` contains all of the html for forms that are being used by thickbox. 

`ajax_processing.php` contains all of the processing (eventually sql insert/updates, etc) that utilize the 
database classes - this is where data is sent after being entered in the forms 

`header.php` and `footer.php` are defined within /templates/ directory. 

`user.php` and `setuser.php` are used for authentication. 

`/css/styles.css` is the general css file used by all pages in coral. 

### Javascript 
All javascript code is stored under `/js/` directory.  This directory contains javascript for base pages
(`index.php`, `admin.php`) where the names of files correspond with the javascript file name. (e.g. 
`admin.php` uses `admin.js`) 

The directory `/js/plugins/` directory contains third party javascript (jquery library, autocomplete, 
thickbox and other plugins) . 

The `/js/forms/` directory contains all javascript files corresponding to the thickbox forms that are 
generated from `ajax_forms.php` 

### Naming standards 
If you would like to contribute code / database changes to the project it is recommended that you stay
within the following naming conventions. 

#### Database Naming:
 
* Attribute and entity names in singular form and using present tense 
* Entity names are uppercased with no spaces or underscores between words (camel case) 
* Attribute names have first word lower cased, subsequent words have first letter upper case 
    * e.g. documentID, sentDate, documentText 
* Primary keys are always Auto Incrementing Integers beginning with the table name and ‘ID’ 
suffix 
    * e.g. for the “Document” table, “documentID” is the name of the primary key 
    * (note that the generic database object expects this naming convention – if you do not use this name, you must override the primary key name in the class) 
* When possible, attribute names are suffixed with class words 
    * Code - Has a list of possible values e.g. INV, ENC 
    * ShortName - Name 
    * Identifier (ID)  - Unique Identifier, generally surrogate key 
    * Number - Numeric value 
    * Indicator (Ind) - A Boolean value (0/1)
    * Date - Date 
    * DateTime - Date and time stamp 

#### Code: 
* Refer to previous sections for directory structure, script locations and script naming. 
* Variable, class and attribute names mimic the database standards with camel case. 
* Method names are prefixed with:  
    * Is – Answers a question, returns true/false, e.g. for User class `isAdmin()` method 
    * Get – retrieves a value 
    * Set – sets a value

## Installation 
See the INSTALL.md file that comes with Coral.
[Here is the master version (unstable developement branch)](https://github.com/tuxayo/Coral/blob/master/INSTALL.md)

## Upgrades 
Upgrades to CORAL will be announced through the CORAL ERM Listserv.  If you wish to be added, please 
consult http://coral-erm.org or email coral-admin@listserv.nd.edu directly. 

In general, small upgrades with simple coding changes will not be given their own version numbers.  If
an institution notifies us about a bug we will let them know directly when the bug fix is available.  
Versioning will happen when there is a database structure change or configuration file change. 

When performing upgrades your configuration file (`/admin/configuration.ini`) should always be backed 
up first so that when you check out the new code you are sure to not overwrite it. 

After you have checked out the new code through GitHub, there will be a file called `UPGRADE_README` in 
the install directory which will detail the database changes and configuration changes incorporated in
that version change. 

As with the Installation, you have two choices for how to upgrade – either manually or web install.   

For the web install, go to `/install/update.php` and follow the instructions on the screen.  

For the manual install, refer to the `UPGRADE_README` file in the install directory for instructions on 
how to upgrade – instructions may be different depending on what types of changes are included with 
the upgrade. 

**After performing upgrade, be sure to remove your `/install/` directory.**

**Comment by tuxayo** [comment]
Completed the dependencies section with all the info that I could gather.

**Comment by scottvieira** [comment]
I received your message.  A few things to note.  We are getting real close to moving the documentation into the Coral-erm/documentation repo.    You can find our working copy here:  https://github.com/scottvieira/Documentation

Please note that the content is not current.  We need to finish updating the existing documentation in markdown and then create a new section for CORAL 2.0.   Any suggestions are definitely welcome.

The Web Committee is still learning how Github works so bear with us and this is a big part of why we are working in a separate repo for the moment. 

We have a SC meeting this Monday.  I need to discuss whether I can pull all the technical documentation out of the wiki and start having it updated in the documentation repo like you have done with your pull request.  I think if we needed to do this, that we could go ahead and move our working copy of the documentation repo over so that you and others can start contributing.  I see your pull request working well with that, but not until after I get our copy moved over and SC approves moving all the technical documentation over.  What I don't want is multiple places getting updated simultaneously.

**Comment by scottvieira** [comment]
@jeffnm To clarify what I need to do here:  would it help if I created a separate install.md file in the documentation based on what Victor has put together, so ongoing as discussed here, you would be able to use install.md for the installer?  If I merged this pull request, I would need to update the Technical Documentation on the doc repo accordingly since I have already migrated it.

**Comment by jeffnm** [comment]
@scottvieira creating an install.md in the documentation would be fine. If we do that, then the README.md here should provide a link to that documentation since some users will be trying to install from the README.md file.  

I wonder, would it be bad to keep installation directions in the code repository (the way Victor is doing here) and usage documentation in your documentation repository? You need to have the code to install it and the people doing those two tasks are often different. You could maintain an installation page in your documentation that instructs people to follow the installation instructions that are maintained with the code. 

Just a thought. If we keep everything in the documentation repository, there may be more cases in the future where a developer documents something in the code and we need to migrate it to the documentation repository. But go ahead and do whatever works best for maintaining the main documentation. If you tell me installation instructions go in a particular file in there, that's where we'll put them. :)

**Comment by tuxayo** [comment]
@scottvieira It was mostly to not loose some detailed notes that I took about the install process and allow @jeffnm to have an up to date base for the 2.0 installer. That's not a problem if it's not merged so do what is the more convenient to maintain in the long term.

**Comment by benheet** [comment]
Did the discussion on this lead to a decision not to merge? If we are ok (and don't lose anything important) by not merging this then let's go ahead and close it and let Scott and the WC complete their documentation work.

**Comment by jeffnm** [comment]
@benheet I believe we've decided not to merge this, but I'm not sure if we need any information from it still or not, so let's leave it open a little longer.

**Comment by tuxayo** [comment]
A part of this PR is the addition of more details, so even if the instructions are not moved into the repo, some of this should at least be merged with the current doc.

**Comment by jeffnm** [comment]
I'm not going to reopen this pull request since we have the new documentation in place in its own repository.

**Pull request closed without merging**
