### PR TITLE
Accessibility

### PR DESCRIPTION
**Pull request by veggiematts**
Currently, Coral does not follow accessibility guidelines that much. This patch aims to improve that. There is much more to do, but this is a start.

This patch mainly does the following:
- Add titles to links
- Add alt descriptions to image links
- Fix some form labels

### CODE REVIEW

**Comment by jeffnm** [comment]
There are some conflicts on this request now that the <?= tags were removed. Sorry about that. Could you update it and then we can merge this in.

**Comment by remocrevo** [comment]
I just learned of the the A11y Project (http://a11yproject.com/), for "making web accessibility easier". I'm not suggesting that this pull request needs to add more changes from that site, but it may be worth creating a new Issue to address any broader accessibility needs in CORAL, and the a11y project provides some useful tools and tips for thinking about that.

**Comment by benheet** [comment]
@veggiematts do you have time to address the conflicts?

**Comment by benheet** [comment]
@veggiematts if you can address the conflicts then this can be merged in and we'll address the a11y project with a new issue.

**Comment by benheet** [comment]
@PaulPoulain can you all resolve the conflicts on this one?

**Comment by jeffnm** [comment]
@PaulPoulain if these conflicts can be resolved, I'd like to include this PR in the 2.0 beta.

**Comment by veggiematts** [comment]
I had a hard time rebasing the existing patch to master, so I created a new patch on master, see #147

**Pull request closed without merging**
