### PR TITLE
Use composer to manage API dependencies

### LINKED ISSUE #287: Resource: Use Composer to manage API dependencies
This will allow the API feature in the Resource module to be used without manual download and installation of the Flight dependency.

Composer is already being used to manage dependencies for the API Client example and for the Codeception test suite.

### PR DESCRIPTION
**Pull request by jsavell**
Resolves #287

### CODE REVIEW

**Comment by jcraitz** [comment]
Thank you for submitting this one.  Was going to suggest we do this.

**Comment by veggiematts** [comment]
Since we're already using composer in Coral, I'm in ok with using it also for the API.
However, merging this will break the API for people already using it.
How do we handle this ?

**Comment by xsong9** [comment]
We are using the Resources API on a daily basis now. Is this change going to break this one? If so, please hold off on the change until you have a solution. Thanks!

**Comment by jcraitz** [comment]
At least for us it's not going to be a difficult change at all.  If people were using it as it was documented before, then they downloaded the package separately in the Flight folder.  Making the proposed change will add a separate vendor folder.  No conflicts there.  And the maintainer simply deletes the old Flight folder.

**Comment by xsong9** [comment]
Good to know it will not break our API. Is someone going to test it before production? We are ok if the test goes through.

**Comment by jcraitz** [comment]
I have tested the same change in a previous version.  It's fine.

**Comment by jsavell** [comment]
@veggiematts It does require re-following the updated API installation instructions, but that doesn't seem like too much of a burden.

If it is too much of a burden, we could support both Composer and manual dependency approaches simultaneously by having the code check for the presence of Flight under `vendor`, fall back to check the previously recommended Flight manual install location.

Depending on the result, the code can conditionally include the autoloader or a direct include of Flight.

**Comment by t4k** [comment]
I added a documentation label to the parent issue. The reconfiguration of the dependency should be added to the Release Notes.

**Pull request merged**
