### PR TITLE
Issue 360: PHP 7.2 compatibility

### PR DESCRIPTION
**Pull request by veggiematts**
PR for Issue #360, using provided shell script.

### CODE REVIEW

**Comment by veggiematts** [comment]
Not tested yet, and I think statements like this : `require_once "common/Object.php";` should also have been modified.

**Comment by veggiematts** [comment]
Tested quickly with the follow-up, seems ok. Help wanted for some more tests.

**Comment by jeffnm** [comment]
@veggiematts I messed up somehow. I was pulling your `biblibre:Issue_360_php_compat` branch into my  `jeffnm:travis_ci_testing` branch, but it looks like my commits from there have all ended up in on your branch too. I don't really understand how that happened. 

I didn't think I had permissions to commit or merge to the Biblibre repository, but that seems to be what has happened, and I don't see anyway to reset it back to the previous state. The only explanation I can think of is that there was a merge conflict (I had renamed my Auth module's Object class already on that branch), and somehow in the process of resolving that it must have pushed my changes back to your repo. I wonder if it's because this PR was opened to CORAL-ERM's repo and I have permission through the CORAL-ERM organization to push changes back to the source branch of open pull requests? 

On the plus side, the travis-ci integration is working well enough that it ran a passing build check on this pull request now that my changes for that are included? Sorry! 

Let me know if I can help clean things up somehow.

**Comment by veggiematts** [comment]
That's... strange. Anyway, I just pushed-force on the branch to revert it back to its previous state.

**Comment by jeffnm** [comment]
Thanks!

**Comment by Alleboom** [comment]
Hey Veggiematts, I made the same changes on our internal environement independently (before finding this issue) and it seems to be working ok. I'll let you know if I run into any issues.

**Comment by veggiematts** [comment]
Thanks for the feedback @Alleboom.
@jeffnm , @t4k , are we merging this ?

**Comment by t4k** [comment]
It looks like a relatively simple change, and @jeffnm says it passed some rudimentary tests, so I would say go for it. It'll be easier to debug if need be when I am more actively working with the development branch locally.

**Pull request merged**
