### PR TITLE
Remove PHP Shorthand to be consistent with rest of code

### PR DESCRIPTION
**Pull request by doug-hahn**

### CODE REVIEW

**Comment by remocrevo** [comment]
For the record, here's the discussion where we concluded that the shorthand "<?=" was acceptable:
https://github.com/ndlibersa/auth/pull/3

But it does appear that the translation code in other modules (besides Auth) uses the full echo syntax.  I don't think we need to be strict about consistency in this case, especially if there are cases where the shorter syntax helps readability of the code.  But I generally agree that consistency is good.

**Comment by benheet** [comment]
What was the action item for this from today's call? Was it to merge or no?

**Comment by techsvcslib** [comment]
Merge.

Steve

**Comment by jeffnm** [comment]
Great. I'll merge it.

**Pull request merged**
