### PR TITLE
Workflow enhancements: restart, archive and edit workflow

### PR DESCRIPTION
**Pull request by veggiematts**
**New features:**
- Restart a completed workflow: Users shall be provided the ability to restart a new workflow by
  selecting a workflow from a pre-defined workflow list or restart the current completed workflow.

workflow_1
workflow_2
- Provide ability to archive previous workflows: Previously completed workflows contain valuable
  information, such as date when tasks are completed, and such information shall be kept.

workflow_3
- Provide the ability to add a step in the workflow for a particular resource: The ability to add a step
  offers users greater flexibility to determine a customized workflow for a specific resource. CORAL
  provides a globalized add a step function in the Admin section, which applies to all resources
  associated with this workflow, not on individual resource level.

workflow_4
workflow_5
workflow_6

### CODE REVIEW

**Comment by benheet** [comment]
Can you only archive a completed workflow or can you archive one still in progress? If the latter, what happens when you archive an in progress workflow? does it mark it as complete?

**Comment by xsong9** [comment]
Ben, yes, you can only archive a completed workflow. More specifically once a workflow is completed, it'll be archived automatically. Let me know if you have more question about this. Thanks!

**Comment by benheet** [comment]
@xsong9 if i have only one workflow and it is completed does it display on the routing tab without having to click another 'display archived workflows'? I do not think that a completed workflow should be hidden automatically. I'd rather keep the complete workflow and archive workflow feature separate. Automatically archiving (and hiding behind an extra link) a completed workflow would not be optimal for folks that don't intend to use the archive workflow feature which is mostly only relevant when there are multiple workflows on the same record.

**Comment by benheet** [comment]
I'm not suggesting any changes to that functionality with my comment, only looking for clarification. I'd be fine with this coming and submitting an issue for any modifications that we'd want to make.

**Comment by xsong9** [comment]
@benheet A completed workflow will be archived automatically but it will not disappear from the routing tab until a new workflow is restarted. Hope this cleared your confusion.

**Comment by xsong9** [comment]
#9

**Comment by benheet** [comment]
There are no conflicts noted for this pull request. If NCSU agrees to update the relevant documentation for the v2.0 launch then I suggest that this be merged now and we'll deal with problems later. This makes significant changes and I'd rather see it included in v2.0 launch then be a new change soon after. To be clear I'm proposing we forgo our 2nd party testing workflow and just merge this one.

**Comment by jeffnm** [comment]
I'm ok with that as long as the 2.0 Beta gets some more thorough testing.

**Comment by xsong9** [comment]
We will update the documentation for the v2.0 launch.

**Comment by benheet** [comment]
@veggiematts can you resolve the conflicts on this pull request?

**Comment by benheet** [comment]
@xsong9 thank you for your willingness to contribute the documentation. please consult with @scottvieira on adding your documentation contributions to the v2.0 documentation.

**Pull request merged**
