### PR TITLE
issue 84 merge common files between modules

### PR DESCRIPTION
**Pull request by tuxayo**
Here is the diff for the commit "Merge almost all common js and css files between modules" which was filtered with `git show HEAD --diff-filter=M` to hide the file creations and deletions which prevented seeing the edits.
https://framagit.org/snippets/252

### CODE REVIEW

**Comment by tuxayo** [comment]
Also I deleted these files that were included **nowhere**

CalendarPopup.js 
jquery.tooltip.min.js
jquery.tooltip.pack.js

The testing was navigating to all modules main pages + admin pages + opening some forms. With the browser networking tool opened to spot any 404. I know that there are pages that I don't know how to access yet.

**Comment by veggiematts** [comment]
Good call on keeping the various jquery versions. It's a first step to unify without breaking compatibility.

**Comment by tuxayo** [comment]
Conflict solving is required. As my internship ended I can no longer maintain this pull request. Anyone is free to "adopt" it.

**Comment by benheet** [comment]
Does anyone have time to take ownership of this one? If not, should we close it and let it remain an open issue? what would be best practice?

**Comment by jeffnm** [comment]
I'm not going to move this pull request to the development branch since it is not maintained.  I will leave it open a little longer in case someone decides to step up and take care of it. However, if that doesn't happen this year, I think we'll be better off closing it and starting over whenever someone is ready to try again.

**Comment by remocrevo** [comment]
This has been replaced by PR #196 .

**Pull request closed without merging**
