### PR TITLE
Foundations of test suite

### PR DESCRIPTION
**Pull request by tuxayo**
See #114

Section "Codeception + real browser (PhantomJS)"

### CODE REVIEW

**Comment by tuxayo** [comment]
Wait, `/tests` shouldn't be accessible from the webserver. Does putting a .htaccess with [this content](https://github.com/Coral-erm/Coral/blob/master/management/admin/.htaccess) is enough?

**Comment by remocrevo** [comment]
@tuxayo Thanks for your work on this!  Is it common to include the composer.lock file in a code repository, or is that dependent on a local server's configuration?

**Comment by tuxayo** [comment]
@remocrevo Yes composer.lock is necessary as it freezes the versions of the dependencies. To ensure we all use for example PhantomJS `2.1.1` and not some random `2.X.Y` version as the composer.json only specifies `> 2.0.0`

It avoids issues due to different versions without having to manually set one exact version in composer.json

https://getcomposer.org/doc/01-basic-usage.md#composer-lock-the-lock-file

**Comment by jeffnm** [comment]
The framework seems to be working. I was able to install the pieces and get things set up, but when I run the `bin/codecept` command as described in TESTS.md the `ResourcesCept` test fails. Looking at the generated screenshot and logs it seems that it is trying to enter the form information before the AJAX form loads. 

This is the screenshot of the step 2 (`Fill field "#titleText","test resource"`) failure. If I do it manually I get the form to load properly - that bar only flashes on the screen momentarily. 

resourcescept fail

I just ran it with php 5.5 and 7.0 on localhost.

**Comment by tuxayo** [comment]
@jeffnm I've never encountered this on the 4 machine where I ran the test a thousand times in a row. What a bad surprise. I added a step to ensure that the form loads, can you try again?

**Comment by jeffnm** [comment]
@tuxayo Thanks for all your work on this!  I was testing on a fresh install, so once I created a ResourceType your tests passed all assertions. I tested php 5.5 and php 7.0 and this test ran and passed all assertions on both. 

I did check that my lack of a Resource Type was not the problem with the previous commit, but that commit still fails with the incomplete modal screenshot, even after adding a Resource Type. This latest commit works though, so that's great!

**Comment by tuxayo** [comment]
> I did check that my lack of a Resource Type was not the problem with the previous commit, but that commit still fails with the incomplete modal screenshot, even after adding a Resource Type.

Thanks for double checking this. We now have the confirmation that there can be some issues related to loading times that happen on one machine but never happen on others. That will cause bad surprises but the fix will be simply adding a generic `$I->waitForPageToBeReady();` or a specific `waitForElement` or `waitForText`

**Comment by tuxayo** [comment]
Surpersesded by #118

**Pull request closed without merging**
