### PR TITLE
Statistics and yearly costs dashboards

### PR DESCRIPTION
**Pull request by veggiematts**
This PR adds two dashboards: resource statistics and yearly costs. Both dashboards can be exported as CSV.

Data can be filtered by:
 - resource type, subject or acquisition type on resource level.
 - order type or cost details on acquisition level.

Data can be grouped by resource type, subject or acquisition type, with sub-totals.

dashboards_1

dashboards_2

### CODE REVIEW

**Comment by veggiematts** [comment]
resources/templates/header.php contains windows line breaks on the whole file, hence the merge conflict. Is this intended ? I thought we had a commit to get rid of those...

**Comment by fondrenlibrary** [comment]
the Fund Pull Down menu in the Edit Cost Information Popup  is blank even though test funds have been added via the Admin Page

**Comment by veggiematts** [comment]
@fondrenlibrary Are you sure the bug you describe comes from this dev? I cannot reproduce it. Did you check on your instance that the funds are properly displayed on master and not on this branch?

**Comment by veggiematts** [comment]
Yes, please.

**Comment by fondrenlibrary** [comment]
using the a local dev instance clears the issue. But I see the dashboards generate no list at all after I added three resources with acquisition info.
image
image

image

**Comment by veggiematts** [comment]
@fondrenlibrary That makes sense. Enhanced cost history is disabled on your instance. Since the dashboards are year-based, and years are not available when enhanced cost history is disabled, the dashboards have nothing to show.
Could you please try again with enhanced cost history enabled ?
In the meantime, I've added a patch that disable the dashboards when enhanced cost history is disabled.

**Comment by fondrenlibrary** [comment]
After enhancedCostHistory is set to Y and year info is added to each payment entry, now I can see statistic  list in the Statistics Dashboard, but the Yearly Cost dashboard still doesn't produce anything. The patch just committed by you works as expected.

**Comment by veggiematts** [comment]
Do you have any error message in the logs?

**Comment by fondrenlibrary** [comment]
[Thu Jan 04 10:45:55.849998 2018] [:error] [pid 108802] [client 10.74.22.178:54453] PHP Notice:  Undefined index: http_lang in /var/www/html/CoralMaster/common/common_directory.php on line 93, referer: http://10.74.22.184/CoralMaster/resources/dashboard_yearly_costs.php
[Thu Jan 04 10:45:55.850022 2018] [:error] [pid 108802] [client 10.74.22.178:54453] PHP Stack trace:, referer: http://10.74.22.184/CoralMaster/resources/dashboard_yearly_costs.php
[Thu Jan 04 10:45:55.850030 2018] [:error] [pid 108802] [client 10.74.22.178:54453] PHP   1. {main}() /var/www/html/CoralMaster/resources/ajax_htmldata.php:0, referer: http://10.74.22.184/CoralMaster/resources/dashboard_yearly_costs.php
[Thu Jan 04 10:45:55.850035 2018] [:error] [pid 108802] [client 10.74.22.178:54453] PHP   2. include_once() /var/www/html/CoralMaster/resources/ajax_htmldata.php:20, referer: http://10.74.22.184/CoralMaster/resources/dashboard_yearly_costs.php
[Thu Jan 04 10:45:55.850040 2018] [:error] [pid 108802] [client 10.74.22.178:54453] PHP   3. require_once() /var/www/html/CoralMaster/resources/directory.php:23, referer: http://10.74.22.184/CoralMaster/resources/dashboard_yearly_costs.php
[Thu Jan 04 10:45:55.857592 2018] [:error] [pid 108802] [client 10.74.22.178:54453] PHP Notice:  Undefined variable: query_where in /var/www/html/CoralMaster/resources/admin/classes/common/Dashboard.php on line 104, referer: http://10.74.22.184/CoralMaster/resources/dashboard_yearly_costs.php
[Thu Jan 04 10:45:55.857610 2018] [:error] [pid 108802] [client 10.74.22.178:54453] PHP Stack trace:, referer: http://10.74.22.184/CoralMaster/resources/dashboard_yearly_costs.php
[Thu Jan 04 10:45:55.857618 2018] [:error] [pid 108802] [client 10.74.22.178:54453] PHP   1. {main}() /var/www/html/CoralMaster/resources/ajax_htmldata.php:0, referer: http://10.74.22.184/CoralMaster/resources/dashboard_yearly_costs.php
[Thu Jan 04 10:45:55.857623 2018] [:error] [pid 108802] [client 10.74.22.178:54453] PHP   2. include() /var/www/html/CoralMaster/resources/ajax_htmldata.php:24, referer: http://10.74.22.184/CoralMaster/resources/dashboard_yearly_costs.php
[Thu Jan 04 10:45:55.857629 2018] [:error] [pid 108802] [client 10.74.22.178:54453] PHP   3. Dashboard->getQueryYearlyCosts() /var/www/html/CoralMaster/resources/ajax_htmldata/getDashboardYearlyCosts.php:20, referer: http://10.74.22.184/CoralMaster/resources/dashboard_yearly_costs.php
[Thu Jan 04 10:45:55.859322 2018] [:error] [pid 108802] [client 10.74.22.178:54453] PHP Fatal error:  Uncaught exception 'Exception' with message 'There was a problem with the database: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM Resource R\n                    LEFT JOIN ResourcePayment RP ON RP.resourceI' at line 10' in /var/www/html/CoralMaster/resources/admin/classes/common/DBService.php:52\nStack trace:\n#0 /var/www/html/CoralMaster/resources/admin/classes/common/DBService.php(91): DBService->checkForError()\n#1 /var/www/html/CoralMaster/resources/admin/classes/common/Dashboard.php(115): DBService->processQuery('SELECT\\n        ...', 'assoc')\n#2 /var/www/html/CoralMaster/resources/ajax_htmldata/getDashboardYearlyCosts.php(21): Dashboard->getResults('SELECT\\n        ...')\n#3 /var/www/html/CoralMaster/resources/ajax_htmldata.php(24): include('/var/www/html/C...')\n#4 {main}\n  thrown in /var/www/html/CoralMaster/resources/admin/classes/common/DBService.php on line 52, referer: http://10.74.22.184/CoralMaster/resources/dashboard_yearly_costs.php

**Comment by veggiematts** [comment]
Ok, my guess is that the query crashed because no cost details were defined. Can you confirm?
This patch should makes the query work with or without cost details.

**Comment by fondrenlibrary** [comment]
Is the payment amount the cost?  otherwise, where to put it?
image

**Comment by veggiematts** [comment]
No, I was referring to the Cost Details, which can be defined in Admin -> Cost Details, and are displayed as a dropdown list in the "Filter on payments" section of the dashboard left menu.

**Comment by fondrenlibrary** [comment]
It and its newest patch works as expected.

**Comment by xsong9** [comment]
Can we add an export button on the result page? I imagine users would want to look at the results first, and then export it for further exploration. Currently, users have to go back to the dashboard main page and then export.

**Comment by veggiematts** [comment]
See #415

**Comment by dineshranjan** [comment]
The yearly cost dashboard should include the cost with the currency type used for the resource for better understanding of the details represented.

**Pull request merged**
