### PR TITLE
Fixes issue #418: Cost history numeric error

### PR DESCRIPTION
**Pull request by sekjal**
Replaces all commas in a proposed amount, not just 1.  Only comes up with very expensive items....

### CODE REVIEW

**Comment by poacherone** [comment]
Tested, and works like a charm! I would suggest adding another line though: 
pAmount = pAmount.replace(/\s/g,'');

This will also fix any whitespace characters, in case they where added by mistake or (as in our case) by choice of currency display.

**Comment by veggiematts** [comment]
"This will also fix any whitespace characters, in case they where added by mistake or (as in our case) by choice of currency display."

Can you elaborate on this ?

**Comment by poacherone** [comment]
We display currency with a space for thousands. Like: "10 000", instead of 10,000. It is also easy to add a trailing whitespace by mistake (say "10,000 "). The second line will strip them.

**Comment by veggiematts** [comment]
Agreed. @sekjal can you update your PR to include @poacherone proposal ?

**Comment by veggiematts** [comment]
This should have been fixed with #576 .

**Pull request closed without merging**
