### PR TITLE
Refactor of Queue HTML,CSS, and JS

### PR DESCRIPTION
**Pull request by jsavell**
This PR refactors the Queue pipeline to reduce code duplication, increase maintainability, and simplify future enhancement.

### CODE REVIEW

**Comment by jeffnm** [comment]
Thanks @jsavell. I haven't tested it yet, but looking through the changes they look like good changes.

**Comment by jeffnm** [comment]
@t4k Would you be wiling to review this PR?

**Comment by t4k** [comment]
I'll review, no problem.

**Comment by t4k** [comment]
I tested this locally and it seems to have the same functionality with and without the patch.

What is the next step? I believe I have the authority to merge. Shall I do it?

**Comment by jeffnm** [comment]
@t4k Thanks for testing. If you are able to merge it, go ahead and do so.

**Pull request merged**
