### PR TITLE
Issue 601: Keep search parameters in resource module

### PR DESCRIPTION
**Pull request by veggiematts**
Background, see Issue #601 
 
This patch fixes the previously existing behavior that was broken:

 When going back from a resource detail to the index page using the Home menu
 link or using the back button of the browser, the search parameters and results
 are kept.

This patch is not very pretty code-wise, so if anyone has a better solution, they're welcome to make another patch.
If not, this can be a quickfix for the time being.

### CODE REVIEW

**Comment by sbouis** [comment]
I have just tested it on Chrome. It works for almost all the search exept for "fund" and "relationship".
For those two, when you click on "home" or use the back button, you retrieve all the resources.

**Comment by veggiematts** [comment]
Thanks for the feedback @sbouis !
The branch has been rebased to avoir conflicts, and both fund and relationship filters are now kept.

**Comment by veggiematts** [comment]
I'm merging this.

**Comment by poacherone** [comment]
Tested after the rebase, on both Chrome and Firefox, and works as intended! Great work!

**Pull request merged**
