### PR TITLE
Resources: view: remove recordID usage and show ISBN, ISSN, etc in resource list  #36

### PR DESCRIPTION
**Pull request by tuxayo**
Review commit by commit.

### CODE REVIEW

**Comment by tuxayo** [comment]
Result:

capture d ecran_2016-07-12_14-51-55

capture d ecran_2016-07-12_14-51-37

**Comment by veggiematts** [comment]
Reviewed & tested ok.

**Comment by tuxayo** [comment]
Rebased with master. A lot of conflicts (I had the great idea to also clean Resources.php in another branch...) but they where hard to solve and reviewing the diff again showed not apparent issue.

**Comment by fondrenlibrary** [comment]
Tested and acceptable.

**Comment by tuxayo** [comment]
Rebased with master and solved conflicts, no particular issue.

**Comment by benheet** [comment]
this looks like its been reviewed and tested and should be ready to merge? anyone have concerns?

**Comment by techsvcslib** [comment]
I don't have a problem with this except that it appears that this completely removes the ability within the UI to search by record ID. I am not in favor of that but if others disagree, I don't feel strongly enough about it.

**Comment by benheet** [comment]
this has conflicts now. @veggiematts  can you assess how difficult it will be to resolve the conflict? if it can be resolved then i propose it be merged and we then create a new issue to restore the record ID search somewhere within the UI.

**Comment by veggiematts** [comment]
The conflicts have been resolved. As I cannot push to @tuxayo 's repository, we'll need to create another PR for this.

Note that it would be quite trivial to keep the search on RecordID in the main resource search page, and it wouldn't be the only searcheable criteria not displayed in the result list.

**Comment by veggiematts** [comment]
Here it is: #141

**Comment by benheet** [comment]
handled by PR #141

**Pull request closed without merging**
