### PR TITLE
Duplicate workflow

### PR DESCRIPTION
**Pull request by veggiematts**
This PR allows to duplicate a workflow.

It adds a duplicate icon in the workflow list from the admin workflow tab:
duplicate_workflow

### CODE REVIEW

**Comment by veggiematts** [comment]
Anyone willing to test this PR ? It's a fairly easy to test feature, with no database update.

**Comment by jcraitz** [comment]
I'll take a look at this.

**Comment by jcraitz** [comment]
I'm not an official reviewer, but I'll take a look when I can.

**Comment by xsong9** [comment]
We are heavy workflow users here. I'd be glad to test it. Can you send the sandbox link for testing?

**Comment by xsong9** [comment]
Tested and it's working as expected.

**Pull request merged**
