### PR TITLE
Email reminder on workflow steps

### PR DESCRIPTION
**Pull request by veggiematts**
Note: this PR is based on PR #117 and therefore contains all of its commits.

This patch allows to trigger an email reminder after a resource step is assigned to a user.
The delay (day-based) can be configured for every resource step:

mail_reminder

### CODE REVIEW

**Comment by benheet** [comment]
@veggiematts can you say more about what the reminder delay is doing? Is it sending a reminder email to the assigned person x number of days after the workflow step is activated? I don't think the workflow template is the proper place to set email reminders that go to a specific person or group. I'd enable a workflow reminder as a global feature that went to anyone assigned to any active workflow step X days after the step was active (if not yet complete) OR i'd leave it to the individual to select whether they wanted reminders somewhere within the My Queue page. This implementation of a reminder feature seems more complex then it needs to be and I'd rather not see this merged without further discussion.

**Comment by veggiematts** [comment]
It sends a reminder email to the assigned persons (each member of the group assigned to this step) n days after the step has been started, where n is the reminder delay.

I thought the specification was discussed with the community prior to this implementation (in the coral-admin mailing list?)

Maybe @xsong9 can tell us more about what was discussed?

**Comment by xsong9** [comment]
@benheet The email reminder can be enabled in the Edit the Workflow window in the Routing tab associated to a resource. It's part of the local workflow enhancement implementation #117 . Setting a workflow reminder as a global feature will not work because the number of delay days for a step varies depending on a specific resource. For example I have a workflow setup for ebook package acquisition and it includes three steps: licensing, invoicing and setup access. I can use the same workflow for both backfile purchase and frontfile 2017 purchase. The backfile access can be set up right after the purchase, but the frontfile access need to wait until the titles are available, which means a couple of months later or even longer.  With this implementation, I can set up different dates for the access step for the backfile and the frontfile locally. It provides flexibility and can avoid creating separate workflows in the Admin.  

Please let me know if you have more concern or question about this feature.

**Comment by benheet** [comment]
Note this PR contains the commits from #117 but I have reservations about the additional alert features added in this PR. I propose that we return to and merge PR #117 and deal with the additional functionality of this PR later.

**Comment by benheet** [comment]
@veggiematts @xsong9 this pull request has been approved but it has conflicts that need to be resolved before it's merged. Can you take responsibility for resolving the conflicts please?

**Comment by jeffnm** [comment]
I've added the 2.0 beta milestone. If we can get the conflicts resolved in time, we can include it. If not, I'll remove the milestone.

**Comment by veggiematts** [comment]
Conflicts resolved on forked branch, but it somehow doesn't seem to be updated in this PR.

**Comment by veggiematts** [comment]
Don't merge into master yet, there are still issues in this branch.

**Comment by veggiematts** [comment]
Nevermind, the problem was on my coral instance. As far as I'm concerned, we're good to go!

**Comment by jeffnm** [comment]
There aren't any conflicts any more, but I'm seeing a bunch of file changes that should already be in coral-erm/master. For example, all the of the Test Suite files are showing up in this pull request. I guess that's not a problem since the end result will be the same, but it strikes me as odd.

**Comment by veggiematts** [comment]
@jeffnm Do you know what could have caused this?

**Comment by jeffnm** [comment]
@veggiematts I don't. Perhaps something in the way the rebase was done? 

Do you think it's a problem?

**Comment by jeffnm** [comment]
@veggiematts beautiful. I'll merge it.

**Pull request merged**
