### PR TITLE
Fix CSV export

### PR DESCRIPTION
**Pull request by veggiematts**
CSV export is currently broken in devel. This patch fixes it.

### CODE REVIEW

**Comment by veggiematts** [comment]
The notice problem is fixed.
The Mysql 5.7 error seems to be the same as issue #235. However, I don't have a Mysql 5.7 instance right now to develop a fix.

**Comment by t4k** [comment]
I got it working on MySQL 5.7 by adding columns to the GROUP BY clause.

The export is full with no notices now.

One sidenote, our export with 4429 records takes longer than 5 minutes (300 seconds in Apache) and required adjusting the Apache configuration. Is there a way to warn users about this or prevent timeouts? The solution/problem probably calls for a new issue…

**Comment by jeffnm** [comment]
If it's primarily a MySQL 5.7 issue, I'll add that to the known issues for the Beta release and we can merge this.

**Comment by t4k** [comment]
I added a commit to this PR that fixes the issue for MySQL 5.7 so it won't be an issue if this PR is merged.

**Comment by jeffnm** [comment]
OK, in that case, I'll merge it. Thanks!

We can open a new issue for the export time out you found.

**Pull request merged**
