### PR TITLE
2.0.0 rc prep

### PR DESCRIPTION
**Pull request by jeffnm**
This PR updates the SQL to address #205 and also restores a whole bunch of images that got corrupted by accident with the trailing whitespace fix. Some of the images looked ok, but others were way off, so I just restored all of the images to be sure.

### CODE REVIEW

**Comment by t4k** [comment]
I checked master against the current development branch to make sure we note all the resources sql changes since the beta was released. I think this should accurately reflect what should be in the 2.0-beta-to-rc-manual.sql file.

```
$ git diff --ignore-space-at-eol master development -- resources/install/protected/install.sql
diff --git a/resources/install/protected/install.sql b/resources/install/protected/install.sql
index ad7132c..0f85c77 100644
--- a/resources/install/protected/install.sql
+++ b/resources/install/protected/install.sql
@@ -406,7 +406,7 @@ CREATE TABLE  `ResourceNote` (
   `resourceID` int(11) default NULL,
   `noteTypeID` int(11) default NULL,
   `tabName` varchar(45) default NULL,
-  `updateDate` timestamp NOT NULL default '0000-00-00 00:00:00',
+  `updateDate` timestamp NOT NULL default CURRENT_TIMESTAMP,
   `updateLoginID` varchar(45) default NULL,
   `noteText` text,
   PRIMARY KEY  (`resourceNoteID`)
@@ -475,6 +475,7 @@ CREATE TABLE  `ResourceStep` (
   `stepID` int(11) default NULL,
   `stepStartDate` date default NULL,
   `stepEndDate` date default NULL,
+  `archivingDate` DATETIME NULL,
   `endLoginID` varchar(200) default NULL,
   `priorStepID` int(11) default NULL,
   `stepName` varchar(200) default NULL,
@@ -788,6 +789,7 @@ INSERT INTO `AccessMethod` (shortName) values ('Local Host');
 INSERT INTO `AcquisitionType` (acquisitionTypeID, shortName) values (1, 'Paid');
 INSERT INTO `AcquisitionType` (acquisitionTypeID, shortName) values (2, 'Free');
 INSERT INTO `AcquisitionType` (acquisitionTypeID, shortName) values (3, 'Trial');
+INSERT INTO `AcquisitionType` (acquisitionTypeID, shortName) values (4, 'Any');
 
 
 INSERT INTO `AdministeringSite` (shortName) values ('Main Library');
@@ -1367,7 +1369,9 @@ INSERT INTO `RelationshipType` (shortName) values ('General');
 
 INSERT INTO `ResourceFormat` (resourceFormatID, shortName) values (1, 'Print + Electronic');
 INSERT INTO `ResourceFormat` (resourceFormatID, shortName) values (2, 'Electronic');
+INSERT INTO `ResourceFormat` (resourceFormatID, shortName) values (3, 'Any');
 
+INSERT INTO `ResourceType` (resourceTypeID, shortName) values (1, 'Any');
 
 
 INSERT INTO `Status` (shortName) values (‘In Progress’);

```

**Comment by t4k** [comment]
I tried to add to this pull request. I’m not sure if I did it correctly.

**Comment by jeffnm** [comment]
Looks good to me. Thanks! Can you run that file on with your 2.0 Beta database to verify that it generates the expected results?

**Comment by jeffnm** [comment]
I'm going to merge this and create the Master branch pull request.

**Comment by t4k** [comment]
I did run that SQL file locally before I added it here, so I think it should be useful to others.

**Comment by fondrenlibrary** [comment]
Sorry, for my late comment, I think the two lines in 
2.0-beta-to-rc-manual.sql file can't cover all changes made since 
beta.For example, |field archivingDate in table ResourceStep is 
seemingly not covered unless update_restart_and_archiving_a_workflow.sql 
is automatically picked and run by the Beta installer.|
||

|Mang |

**Comment by jeffnm** [comment]
I've updated the development branch with the updated file that I mistakenly thought was already included. Since the release candidate is tagged already there is no way to add that manual file to the  release candidate without tagging a new release, so I've just edited the release notes to point to the github repository's development branch version of the file.

**Comment by t4k** [comment]
I think that will work fine since it is going to be a manual process for those users anyway.

**Comment by fondrenlibrary** [comment]
I agree. Thank you all.

Mang

**Pull request merged**
